#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Install Homebrew and a bundle of recipes
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

else
  # universal-install
  sudo wget -O /usr/local/bin/pacapt \
    https://github.com/icy/pacapt/raw/ng/pacapt
  sudo chmod 755 /usr/local/bin/pacapt
  sudo ln -sv /usr/local/bin/pacapt /usr/local/bin/pacman || true

  pacapt update
  pacapt install zsh tmux neovim nano
fi

if [ ! -d ~/.tmux ]; then
  echo "TMUX Setup"
  cd
  git clone https://github.com/gpakosz/.tmux.git
  ln -s -f .tmux/.tmux.conf
fi

if [ ! -d ~/.config/nvim ]; then
  git clone https://github.com/LazyVim/starter ~/.config/nvim
fi

if [ ! -d ~/.nano ]; then
  git clone https://github.com/scopatz/nanorc.git ~/.nano
fi

yadm alt

echo "Finished"
